- name: Install Git
  apt:
      name: git
      state: present

- name: Install Jenkins Repository
  get_url:
    url: "{{ jenkins_key_rpmUbuntu }}"
    dest: "{{ jenkins_key_rpmUbuntu_dest }}"

- name: Add Jenkins repository to sources.list
  lineinfile:
    path: "{{ item.value.jenkins_source_list }}"
    line: "{{ item.value.url }}"
    create: yes
  loop:
      "{{ lookup('dict',reposUbuntu, wantlist=True) }}"

- name: Update Package Cache
  apt:
    update_cache: yes

- name: "Install Java and Jenkins"
  apt:
      name: "{{ item.value.name }}"
      state: present
  loop:
      "{{ lookup('dict',softwaresUbuntu, wantlist=True) }}"

- name: Enable and Start Jenkins Service
  service:
      name: "jenkins"
      state: started
      enabled: yes